-- MySQL Script generated by MySQL Workbench
-- But edited

DROP TABLE IF EXISTS `cabsBooking` ;
DROP TABLE IF EXISTS `cabsAddress` ;
DROP TABLE IF EXISTS `cabsSuburb` ;
DROP TABLE IF EXISTS `cabsCustomer` ;

-- -----------------------------------------------------
-- Table `cabsCustomer`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cabsCustomer` (
  `email_address` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`email_address`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cabsSuburb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabsSuburb` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `is_eligible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cabsAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabsAddress` (
  `id` INT UNSIGNED NOT NULL,
  `unit_number` VARCHAR(45) NULL,
  `street_number` VARCHAR(45) NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `suburb_id` INT UNSIGNED NOT NULL,
  `customer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_suburb`
    FOREIGN KEY (`suburb_id`)
    REFERENCES `cabsSuburb` (`id`),
  CONSTRAINT `fk_address_customer`
    FOREIGN KEY (`customer`)
    REFERENCES `cabsCustomer` (`email_address`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cabsBooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cabsBooking` (
  `reference_number` INT UNSIGNED NOT NULL,
  `customer` VARCHAR(255) NOT NULL,
  `passenger_name` VARCHAR(255) NOT NULL,
  `status` ENUM('UNASSIGNED', 'ASSIGNED') NOT NULL DEFAULT 'UNASSIGNED',
  `passenger_phone` VARCHAR(20) NOT NULL,
  `dest_suburb` INT UNSIGNED NOT NULL,
  `placement_time` DATETIME NOT NULL,
  `pickup_datetime` DATETIME NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`reference_number`),
  CONSTRAINT `fk_booking_suburb`
    FOREIGN KEY (`dest_suburb`)
    REFERENCES `cabsSuburb` (`id`),
  CONSTRAINT `fk_booking_customer`
    FOREIGN KEY (`customer`)
    REFERENCES `cabsCustomer` (`email_address`),
  CONSTRAINT `fk_booking_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `cabs`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

